apiVersion: v1
kind: Pod
metadata:
  name: rhel7-dev-llvm-toolset
  labels:
    app: rhel7-dev-llvm-toolset
  namespace: evals25-shared-7daa
spec:
  containers:
    - name: rhel7-dev-llvm-toolset   
      image: devtools/llvm-toolset-rhel7
      args:
        - /bin/sh
        - '-c'
        - sleep 30d
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - '-i'
            - '-c'
            - >-
              ls
        initialDelaySeconds: 3
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
        terminationMessagePath: /dev/termination-log
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - '-i'
            - '-c'
            - >-
              ls
